### ISSUE TITLE
Important Notification From SONOFF

### ISSUE THREAD

**Issue by Daniel-zhan-itead** [to4ko/myconfig#1]
As eWeLink will stop provide the support and maintance of current APPID & APP secret on Aug 31th 2020. 

That means that this project may work improperly.

eWeLink will offer a special APPID and APP secret for this project.

@to4ko  Please contact me via the mail 

To: daniel.zhan@itead.cc
and cc: jiale.liu@coolkit.cn

Daniel

**Comment by to4ko** [comment]
Hi. All SONOFF's used re-flashed to ESPHome.
