### ISSUE TITLE
домофон

### ISSUE THREAD

**Issue by edgiru** [to4ko/myconfig#2]
добрый день!
Извиняюсь что пишу тут. Случайно наткнулся на ваш скрип домофона на esp32 domofon.yaml
Не подскажите может есть у Вас статья что и как собрать подключить.
Весь интернет перерыл ищу esp32cam домофон что то на них не кто не делает.
У меня 4 квартиры соседи на этаже хотел собрать на esp32cam простейший домофон 4 кнопки, камера, считыватель карт и меток и сделать согласование между этим самодельным домофоном и в подъезде который стоит много квартирный cifral(по моему) ну естественно все это с mqtt и Home Assistant.

**Comment by to4ko** [comment]
приветствую!

домофон собирал по статье от Николая. 

https://sprut.ai/client/article/1691
