### ISSUE TITLE
ESP32 - Hood K - Kitchen Hood Fan\Light Control, BME280, Dallas and max6675

### ISSUE THREAD

**Issue by emilp333** [to4ko/myconfig#5]
Hi,

I'm very curios about your Kitchen hood fan and light control. Would you have the time to elaborate on what you build and how you implemented it in your fan? 

Thanks :)

**Comment by to4ko** [comment]
> Hi,
> 
> I'm very curios about your Kitchen hood fan and light control. Would you have the time to elaborate on what you build and how you implemented it in your fan?
> 
> Thanks :)


oooo i;m really sorry for being that late with reply - missed this one. 

it's Bosch hood fan unit model DWW061451. All the controls (light and fan) are disconnected from original swithes. 
Relay modules connected to ESP32 are used instead. Further plan - get couple of buttons with led backlight to have manual control over lights and fan.
